---
title: "Spit attribution for small scale excavations"
author: "Clemens Schmid"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Spit attribution for small scale excavations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE}
if (!requireNamespace("plotly", quietly = TRUE)) {
  stop("plotly needed for this vignette to build.",
    call. = FALSE)
}
```

```{r, message=FALSE}
devtools::load_all()
library(plotly)
library(kriging)
library(reshape2)
library(dplyr)
library(magrittr)
```

```{r}
edges <- data.frame(
  x = c(0, 3, 0, 3, 0, 3, 0, 3),
  y = c(0, 0, 0, 0, 1, 1, 1, 1),
  z = c(0, 0, 2, 2, 0, 0, 2, 2)
)

df1 <- data.frame(
  x = c(rep(0, 6), seq(0.2, 2.8, 0.2), seq(0.2, 2.8, 0.2), rep(3,6)),
  y = c(seq(0, 1, 0.2), rep(0, 14), rep(1, 14), seq(0, 1, 0.2)), 
  z = c(1+0.1*rnorm(6), 1+0.1*rnorm(14), 0.8+0.1*rnorm(14), 0.8+0.1*rnorm(6))
)

df2 <- data.frame(
  x = c(rep(0, 6), seq(0.2, 2.8, 0.2), seq(0.2, 2.8, 0.2), rep(3,6)),
  y = c(seq(0, 1, 0.2), rep(0, 14), rep(1, 14), seq(0, 1, 0.2)),
  z = c(0.5+0.1*rnorm(6), 0.5+0.1*rnorm(14), 0.4+0.1*rnorm(14), 0.4+0.1*rnorm(6))
)
```

```{r fig.width=7, fig.height=5}
plot_ly(edges, x = x, y = y, z = z, type = "scatter3d", mode = "markers")
```

```{r }
lpoints <- list(df1, df2)
```

```{r }
maps <- kriglist(lpoints, lags = 3, model = "spherical")
```

```{r fig.width=7, fig.height=5}
surf1 <- spatialwide(maps[[1]]$x, maps[[1]]$y, maps[[1]]$pred, 3)
surf2 <- spatialwide(maps[[2]]$x, maps[[2]]$y, maps[[2]]$pred, 3)

x1 <- as.numeric(colnames(surf1))
y1 <- as.numeric(rownames(surf1))
z1 <- as.matrix(surf1)
x2 <- as.numeric(colnames(surf2))
y2 <- as.numeric(rownames(surf2))
z2 <- as.matrix(surf2)

vis <- plot_ly(x = x1, y = x1, z = z1, type = "surface", showscale = FALSE
  ) %>%
  add_trace(data = df1, x = x, y = y, z = z, 
            mode = "markers", type = "scatter3d", 
            marker = list(size = 4, color = "green", symbol = 104)
  ) %>%
  add_trace(x = x2, y = x2, z = z2, type = "surface", showscale = FALSE
  ) %>%
  add_trace(data = df2, x = x, y = y, z = z, 
            mode = "markers", type = "scatter3d", 
            marker = list(size = 4, color = "blue", symbol = 104)
  ) %>% 
  layout(showlegend = FALSE)
  
vis
```

```{r fig.width=7, fig.height=5}
hexatestdf <- data.frame(
  x = c(1.5, 1.5, 2.2, 1.8, 1.3, 1.2, 1.7, 2),
  y = c(0.2, 0.4, 0.2, 0.4, 0.15, 0.35, 0.2, 0.4),
  z = c(0.2, 0.1, 0.2, 0.1, 1.5, 1.6, 1.5, 1.6)
)

hexatest <- as.matrix(hexatestdf)

cx = fillhexa(hexatest, 0.05)
cx <- data.frame(cx)
colnames(cx) <- c("x", "y" , "z")

cuberasterlist <- list(cx)

vis %>% add_trace(data = cx, x = x, y = y, z = z, 
            mode = "markers", type = "scatter3d", 
            marker = list(size = 1, color = "red", symbol = 104)
  )
```

```{r fig.width=7, fig.height=5}
crlist <- posdec(cuberasterlist, maps)

hexa <- data.frame(crlist[[1]])
colnames(hexa) <- c("x", "y", "z", "decision")

a <- filter(
  hexa,
  decision == 0
)

b <- filter(
  hexa,
  decision == 1
)

c <- filter(
  hexa,
  decision == 2
)

vis %>% add_trace(data = a, x = x, y = y, z = z, 
            mode = "markers", type = "scatter3d", 
            marker = list(size = 1, color = "#31a354", symbol = 104)
  ) %>% add_trace(data = b, x = x, y = y, z = z, 
            mode = "markers", type = "scatter3d", 
            marker = list(size = 1, color = "#de2d26", symbol = 104)
  ) %>% add_trace(data = c, x = x, y = y, z = z, 
            mode = "markers", type = "scatter3d", 
            marker = list(size = 1, color = "#2b8cbe", symbol = 104)
  )
```

```{r}
# deci: create a result data.frame which shows the distribution of cube points
deci <- function (crlist) {
  
  # reformat matrizes in crlist to data.frames
  for (i in 1:length(crlist)) {
    crlist[[i]] <- data.frame(crlist[[i]])
    colnames(crlist[[i]]) <- c("x", "y", "z", "decision")
  }
  
  # determine amount of layers
  nl = max(unlist(lapply(crlist, function(x) max(x$decision, na.rm=T))))
  # create result data.frame
  m <- matrix(NA, ncol = nl+1, nrow = 1)
  decision <- data.frame(m)
  names(decision) <- c(0:nl)
  # calculate distribution
  for (crp in 1:length(crlist)) {
    cr <- crlist[[crp]]
    crd <- sort(unique(cr$decision))
    ncr <- nrow(cr)
    for (i in 1:length(crd)) {
      decision[crp, names(decision) == crd[i]] <- nrow(filter(cr, decision == crd[i]))/ncr*100
    }
  }
  return(decision)
}

deci(crlist)
```