// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fillhexa
DataFrame fillhexa(DataFrame hex, double res);
RcppExport SEXP quantaar_fillhexa(SEXP hexSEXP, SEXP resSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type hex(hexSEXP);
    Rcpp::traits::input_parameter< double >::type res(resSEXP);
    __result = Rcpp::wrap(fillhexa(hex, res));
    return __result;
END_RCPP
}
// posdec
DataFrame posdec(DataFrame crlist, List maplist);
RcppExport SEXP quantaar_posdec(SEXP crlistSEXP, SEXP maplistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type crlist(crlistSEXP);
    Rcpp::traits::input_parameter< List >::type maplist(maplistSEXP);
    __result = Rcpp::wrap(posdec(crlist, maplist));
    return __result;
END_RCPP
}
// posdeclist
List posdeclist(List crlist, List maplist);
RcppExport SEXP quantaar_posdeclist(SEXP crlistSEXP, SEXP maplistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type crlist(crlistSEXP);
    Rcpp::traits::input_parameter< List >::type maplist(maplistSEXP);
    __result = Rcpp::wrap(posdeclist(crlist, maplist));
    return __result;
END_RCPP
}
