// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fillhexa
NumericVector fillhexa(SEXP hex, double res);
RcppExport SEXP quantaar_fillhexa(SEXP hexSEXP, SEXP resSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type hex(hexSEXP);
    Rcpp::traits::input_parameter< double >::type res(resSEXP);
    __result = Rcpp::wrap(fillhexa(hex, res));
    return __result;
END_RCPP
}
