# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fills hexahedrons with a systematic point raster
#'
#' https://stackoverflow.com/questions/36115215/filling-a-3d-body-with-a-systematic-point-raster
#'
#' @param hex matrix
#' @param res double
#'
#' @return final matrix
#'
#' @examples
#' hexatestdf <- data.frame(
#'   x = c(0,1,0,4,5,5,5,5),
#'   y = c(1,1,4,4,1,1,4,4),
#'   z = c(4,8,4,9,4,8,4,6)
#' )
#'
#' hexatest <- as.matrix(hexatestdf)
#'
#' cx = fillhexa(hexatest, 0.1)
#'
#' #library(rgl)
#' #plot3d(
#' # cx[,1], cx[,2], cx[,3],
#' # type = "p",
#' # xlab = "x", ylab = "y", zlab = "z"
#' #)
#'
#' @export
fillhexa <- function(hex, res) {
    .Call('quantaar_fillhexa', PACKAGE = 'quantaar', hex, res)
}

#' Test
#'
#' Testdescription
#'
#' @param crlist TODO
#' @param maplist TODO
#'
#' @export
posdec <- function(crlist, maplist) {
    .Call('quantaar_posdec', PACKAGE = 'quantaar', crlist, maplist)
}

